CREATE TABLE IF NOT EXISTS training_plan (
plan_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
department VARCHAR(30),
job VARCHAR(60) NOT NULL DEFAULT "None",
safety_req VARCHAR(3) NOT NULL CHECK (safety_req IN ("Yes", "No")) DEFAULT "No",
sop_req VARCHAR(3) NOT NULL CHECK (sop_req IN ("Yes", "No")) DEFAULT "No",
qms_req VARCHAR(3) NOT NULL CHECK (qms_req IN ("Yes", "No")) DEFAULT "No",
area_fam_req VARCHAR(3) NOT NULL CHECK (area_fam_req IN ("Yes", "No")) DEFAULT "No",
area_fam_hrs REAL DEFAULT 0.0,
le_req VARCHAR(3) NOT NULL CHECK (le_req IN ("Yes", "No")) DEFAULT "No",
le_hrs REAL DEFAULT 0.0,
test_req VARCHAR(3) NOT NULL CHECK (test_req IN ("Yes", "No")) DEFAULT "No",
num_test INTEGER DEFAULT 0,
test1_trigger REAL,
test1_pass REAL,
test2_trigger REAL,
test2_pass REAL,
test3_trigger REAL,
test3_pass REAL,
cleanup_req VARCHAR(3) NOT NULL CHECK (cleanup_req IN ("Yes", "No")) DEFAULT "No",
cleanup_hrs REAL DEFAULT 0.0,
changeover_req VARCHAR(3) NOT NULL CHECK (changeover_req IN ("Yes", "No")) DEFAULT "No",
changeover_hrs REAL DEFAULT 0.0,
signoff_req VARCHAR(3) NOT NULL CHECK (signoff_req IN ("Yes", "No")) DEFAULT "No"
);